=== VictorShedko/greenhousemaven/src/test/testresources/greenhouseScheme.XSD
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://by.victor.epam"
        xmlns:ns="http://by.victor.epam"
        elementFormDefault="qualified">
    <element name="flowers">
        <complexType>
            <sequence>
                <element ref="ns:plant"  maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Plant">
        <sequence>
            <element name="visual-parameters" type="ns:Visual-parameters" minOccurs="0" maxOccurs="unbounded"/>
            <element name="growing-tips" type="ns:Growing-tips" minOccurs="0" maxOccurs="unbounded"/>
            <element name="multiplying" type="ns:Multiplying-type" minOccurs="0" maxOccurs="3"/>
            <element name="soil" type="ns:SoilType" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="capriciousness" type="ns:Capriciousness" default="medium"/>
        <attribute name="title" type="ns:PlantTitle" use="required"/>
        <attribute name="origin" type="ns:Origin" use="optional"/>
    </complexType>

    <complexType name="Flower">
        <complexContent>
            <extension base="ns:Plant">
                <sequence>
                    <element name="flowering-time">
                        <complexType>
                            <sequence>
                                <element name="start-month" type="gMonth"/>
                                <element name="end-month" type="gMonth"/>
                            </sequence>
                        </complexType>
                    </element>

                    <element name="possible-inflorescence-color" >
                        <complexType>
                            <sequence>
                                <element  name="color" type="ns:Color" maxOccurs="unbounded"></element>
                            </sequence>
                        </complexType>
                    </element>
                </sequence>

            </extension>
        </complexContent>
    </complexType>

    <complexType name="Visual-parameters">
        <choice>
            <element name="stick-color" type="ns:Color" ></element>
            <element name="leaf-color" type="ns:Color" ></element>
            <element name="height" type="positiveInteger" minOccurs="0" ></element>
        </choice>

    </complexType>

    <complexType name="Growing-tips">
        <choice>
            <element name="heliophilous" type="boolean"></element>
            <element name="watering" >
                <simpleType>
                    <restriction base="positiveInteger">
                        <maxExclusive value="10000"></maxExclusive>
                    </restriction>
                </simpleType>
            </element>
            <element name="min-temperature" type="ns:Temperature" ></element>
            <element name="max-temperature" type="ns:Temperature" ></element>
        </choice>

    </complexType>

    <simpleType name="PlantTitle">
        <restriction base="ID">
            <pattern value="[a-zA-Zа-яА-Я\-']{2,}"/>
        </restriction>
    </simpleType>

    <simpleType name="SoilType">

        <restriction base="string">
            <enumeration value="podzolic"></enumeration>
            <enumeration value="ground"></enumeration>
            <enumeration value="sod-podzolic soil"></enumeration>
        </restriction>


    </simpleType>
    <simpleType name="Origin">

        <restriction base="string">
            <pattern value="([A-ZА-Я][a-zA-ZА-Я\-]+)(\s[A-ZА-Я]*[a-z]+)*"/>
        </restriction>


    </simpleType>
    <simpleType name="Multiplying-type">

        <restriction base="string">
            <enumeration value="leaf"></enumeration>
            <enumeration value="stalk"></enumeration>
            <enumeration value="seed"></enumeration>
        </restriction>


    </simpleType>

    <simpleType name="Temperature">

        <restriction base="positiveInteger">
            <maxExclusive value="60"></maxExclusive>
            <minExclusive value="1"></minExclusive>
        </restriction>


    </simpleType>

    <simpleType name="Capriciousness">
        <restriction base="string">
            <enumeration value="high"></enumeration>
            <enumeration value="medium"></enumeration>
            <enumeration value="low"></enumeration>
        </restriction>
    </simpleType>

    <simpleType name="Color">
        <restriction base="string">
            <enumeration value="white"></enumeration>
            <enumeration value="red"></enumeration>
            <enumeration value="orange"></enumeration>
            <enumeration value="green"></enumeration>
            <enumeration value="yellow"></enumeration>
            <enumeration value="blue"></enumeration>
            <enumeration value="light-green"></enumeration>
            <enumeration value="dark-green"></enumeration>
            <enumeration value="green"></enumeration>
        </restriction>
    </simpleType>
    <element name="plant" type="ns:Plant" ></element>
    <element name="flower" type="ns:Flower" substitutionGroup="ns:plant"></element>

</schema>

=== VictorShedko/greenhousemaven/src/test/testresources/greenhouseLogicError.xml
<?xml version="1.0"?>
<flowers xmlns="http://by.victor.epam"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://by.victor.epam greenhouseScheme.XSD">
    <plant title="heather">

    </plant>

    <error title="lily" capriciousness="high">
        <visual-parameters> <!--ввести общий тип tips  и добавить в него кучу маленьких типов -->
            <height>50</height>
        </visual-parameters>
        <visual-parameters>
            <stick-color>green</stick-color>
        </visual-parameters>
        <growing-tips>
            <heliophilous>true</heliophilous>
        </growing-tips>
        <growing-tips>
            <watering>200</watering>
        </growing-tips>
        <growing-tips>
            <min-temperature>22</min-temperature>
        </growing-tips>
        <growing-tips>
            <max-temperature>41</max-temperature>
        </growing-tips>
        <multiplying>seed</multiplying>
        <soil>podzolic</soil>
        <flowering-time>
            <start-month>--05</start-month>
            <end-month>--07</end-month>
        </flowering-time>
        <possible-inflorescence-color>
            <color>white</color>
            <color>red</color>
            <color>yellow</color>
        </possible-inflorescence-color>
    </error>

    <flower origin="South America" title="orchid">
        <visual-parameters>
            <height>20</height>
        </visual-parameters>
        <growing-tips>
            <heliophilous>true</heliophilous>
        </growing-tips>
        <flowering-time>
            <start-month>--06</start-month>
            <end-month>--10</end-month>
        </flowering-time>
        <possible-inflorescence-color>
            <color>white</color>
            <color>red</color>
            <color>yellow</color>
        </possible-inflorescence-color>

    </flower>
    <flower title="rose">
        <visual-parameters>
            <height>50</height>
        </visual-parameters>
        <visual-parameters>
            <leaf-color>green</leaf-color>
        </visual-parameters>
        <visual-parameters>
            <stick-color>green</stick-color>
        </visual-parameters>
        <growing-tips>

            <watering>200</watering>
        </growing-tips>
        <growing-tips>
            <min-temperature>22</min-temperature>
        </growing-tips>
        <growing-tips>
            <max-temperature>41</max-temperature>
        </growing-tips>
        <flowering-time>
            <start-month>--05</start-month>
            <end-month>--06</end-month>
        </flowering-time>
        <possible-inflorescence-color>
            <color>white</color>
            <color>red</color>
            <color>yellow</color>
        </possible-inflorescence-color>

    </flower>
    <flower title="tulip">
        <visual-parameters>
            <height>50</height>

        </visual-parameters>
        <growing-tips>

            <watering>200</watering>
        </growing-tips>
        <growing-tips>
            <min-temperature>22</min-temperature>
        </growing-tips>
        <growing-tips>
            <max-temperature>41</max-temperature>
        </growing-tips>
        <flowering-time>
            <start-month>--01</start-month>
            <end-month>--03</end-month>
        </flowering-time>
        <possible-inflorescence-color>
            <color>white</color>
            <color>red</color>
            <color>yellow</color>
        </possible-inflorescence-color>

    </flower>
    <flower title="clove">
        <visual-parameters>
            <height>50</height>
        </visual-parameters>
        <visual-parameters>
            <leaf-color>green</leaf-color>
        </visual-parameters>
        <visual-parameters>
            <stick-color>green</stick-color>
        </visual-parameters>


        <growing-tips>
            <watering>300</watering>
        </growing-tips>
        <flowering-time>
            <start-month>--04</start-month>
            <end-month>--05</end-month>
        </flowering-time>
        <possible-inflorescence-color>
            <color>white</color>
            <color>red</color>
            <color>yellow</color>
        </possible-inflorescence-color>

    </flower>

    <plant title="juniper" origin="North-Europe">
        <visual-parameters>
            <height>50</height>

        </visual-parameters>
        <growing-tips>
            <max-temperature>41</max-temperature>
        </growing-tips>
    </plant>

    <plant title="bamboo" origin="East-Asia">
        <visual-parameters>

            <stick-color>green</stick-color>
        </visual-parameters>
        <growing-tips>
            <min-temperature>22</min-temperature>
        </growing-tips>
        <growing-tips>
            <max-temperature>41</max-temperature>
        </growing-tips>
    </plant>

    <plant title="citrus">

    </plant>

    <plant title="mandarin">

    </plant>

    <plant title="yucca">

    </plant>

    <plant title="pineapple">

    </plant>

    <plant title="potato">

    </plant>
</flowers>

=== VictorShedko/greenhousemaven/src/test/testresources/greenhouse.xml
<?xml version="1.0"?>
<flowers xmlns="http://by.victor.epam"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://by.victor.epam greenhouseScheme.XSD">
    <plant origin="North Europe" title="heather">

    </plant>

    <flower title="lily" capriciousness="high">
        <visual-parameters>
            <height>50</height>
        </visual-parameters>
        <visual-parameters>
            <stick-color>green</stick-color>
        </visual-parameters>
        <growing-tips>
            <heliophilous>true</heliophilous>
        </growing-tips>
        <growing-tips>
            <watering>200</watering>
        </growing-tips>
        <growing-tips>
            <min-temperature>22</min-temperature>
        </growing-tips>
        <growing-tips>
            <max-temperature>41</max-temperature>
        </growing-tips>
        <multiplying>seed</multiplying>
        <soil>podzolic</soil>
        <flowering-time>
            <start-month>--05</start-month>
            <end-month>--07</end-month>
        </flowering-time>
        <possible-inflorescence-color>
            <color>white</color>
            <color>red</color>
            <color>yellow</color>
        </possible-inflorescence-color>
    </flower>

    <flower origin="South America" title="orchid">
        <visual-parameters>
            <height>20</height>
        </visual-parameters>
        <growing-tips>
            <heliophilous>true</heliophilous>
        </growing-tips>
        <flowering-time>
            <start-month>--06</start-month>
            <end-month>--10</end-month>
        </flowering-time>
        <possible-inflorescence-color>
            <color>white</color>
            <color>red</color>
            <color>yellow</color>
        </possible-inflorescence-color>

    </flower>
    <flower title="rose">
        <visual-parameters>
            <height>50</height>
        </visual-parameters>
        <visual-parameters>
            <leaf-color>green</leaf-color>
        </visual-parameters>
        <visual-parameters>
            <stick-color>green</stick-color>
        </visual-parameters>
        <growing-tips>

            <watering>200</watering>
        </growing-tips>
        <growing-tips>
            <min-temperature>22</min-temperature>
        </growing-tips>
        <growing-tips>
            <max-temperature>41</max-temperature>
        </growing-tips>
        <flowering-time>
            <start-month>--05</start-month>
            <end-month>--06</end-month>
        </flowering-time>
        <possible-inflorescence-color>
            <color>white</color>
            <color>red</color>
            <color>yellow</color>
        </possible-inflorescence-color>

    </flower>
    <flower title="tulip">
        <visual-parameters>
            <height>50</height>

        </visual-parameters>
        <growing-tips>

            <watering>200</watering>
        </growing-tips>
        <growing-tips>
            <min-temperature>22</min-temperature>
        </growing-tips>
        <growing-tips>
            <max-temperature>41</max-temperature>
        </growing-tips>
        <flowering-time>
            <start-month>--01</start-month>
            <end-month>--03</end-month>
        </flowering-time>
        <possible-inflorescence-color>
            <color>white</color>
            <color>red</color>
            <color>yellow</color>
        </possible-inflorescence-color>

    </flower>
    <flower title="clove">
        <visual-parameters>
            <height>50</height>
        </visual-parameters>
        <visual-parameters>
            <leaf-color>green</leaf-color>
        </visual-parameters>
        <visual-parameters>
            <stick-color>green</stick-color>
        </visual-parameters>


        <growing-tips>
            <watering>300</watering>
        </growing-tips>
        <flowering-time>
            <start-month>--04</start-month>
            <end-month>--05</end-month>
        </flowering-time>
        <possible-inflorescence-color>
            <color>white</color>
            <color>red</color>
            <color>yellow</color>
        </possible-inflorescence-color>

    </flower>

    <plant title="juniper" origin="North-Europe">
        <visual-parameters>
            <height>50</height>

        </visual-parameters>
        <growing-tips>
            <max-temperature>41</max-temperature>
        </growing-tips>
    </plant>

    <plant title="bamboo" origin="East-Asia">
        <visual-parameters>

            <stick-color>green</stick-color>
        </visual-parameters>
        <growing-tips>
            <min-temperature>22</min-temperature>
        </growing-tips>
        <growing-tips>
            <max-temperature>41</max-temperature>
        </growing-tips>
    </plant>

    <plant title="citrus">
        <growing-tips>
            <max-temperature>52</max-temperature>
        </growing-tips>
    </plant>

    <plant title="mandarin">
        <visual-parameters>
            <stick-color>yellow</stick-color>
        </visual-parameters>
    </plant>

    <plant title="yucca">
        <visual-parameters>
            <leaf-color>white</leaf-color>
        </visual-parameters>
    </plant>

    <plant title="pineapple">

    </plant>

    <plant title="potato">

    </plant>

    <plant title="agave">
        <visual-parameters>
            <leaf-color>light-green</leaf-color>
        </visual-parameters>
        <visual-parameters>
            <height>10</height>
        </visual-parameters>
        <soil>ground</soil>
    </plant>

    <flower title="lavender">
        <visual-parameters>
            <height>30</height>
        </visual-parameters>
        <growing-tips>
            <heliophilous>true</heliophilous>
        </growing-tips>
        <multiplying>stalk</multiplying>
        <soil>sod-podzolic soil</soil>
        <flowering-time>
            <start-month>--07</start-month>
            <end-month>--09</end-month>
        </flowering-time>
        <possible-inflorescence-color>
            <color>blue</color>
        </possible-inflorescence-color>
    </flower>
</flowers>
